[package]
name = "trustchain-api"
version = "0.1.0"
authors = ["Trustchain Devs"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trustchain-core = { path = "../trustchain-core" }
ssi = "0.4"
did-ion = "0.1"
anyhow = "1.0.70"
