[package]
name = "trustchain-api"
version = "0.1.0"
authors = ["Trustchain Devs"]
edition = "2021"


[dependencies]
trustchain-core = { path = "../trustchain-core" }
trustchain-ion = { path = "../trustchain-ion" }
ps_sig = { git = "https://github.com/alan-turing-institute/RSS.git", branch = "new_rss" }

async-trait = "0.1"
serde_json = "1.0"
ssi = { git = "https://github.com/alan-turing-institute/ssi.git", branch = "1-rss", features = [
    "http-did",
    "secp256k1",
    "rss",
] }
did-ion = { git = "https://github.com/alan-turing-institute/ssi.git", branch = "1-rss" }
futures = "0.3.28"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["full"] }
