[workspace]
members = [
    "trustchain-core",
    "trustchain-ion",
    "trustchain-http",
    "trustchain-api",
    "trustchain-cli",
    "trustchain-ffi",
    "sovrin-test",
    "trustchain-sovrin"]
resolver = "2"
