[core]
trustchain_data = "TRUSTCHAIN_DATA"
root_event_time = 1666265405
root_event_time_2378493 = 1666971942

[ion]
mongo_connection_string = "mongodb://localhost:27017/"
mongo_database_ion_testnet_core = "ion-testnet-core"

bitcoin_connection_string = "http://localhost:18332"
bitcoin_rpc_username = "admin"
bitcoin_rpc_password = "lWrkJlpj8SbnNRUJfO6qwIFEWkD+I9kL4REsFyMBlow="
