[package]
name = "trustchain-cli"
version = "0.1.0"
authors = ["Trustchain Devs"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "trustchain-cli"
path = "src/bin/main.rs"

[dependencies]
trustchain-core = { path = "../trustchain-core" }
trustchain-ion = { path = "../trustchain-ion" }
ssi = "0.4"
clap = { version = "~4.0", features=["derive", "cargo"] }
serde_json = "1.0"
did-ion = "0.1.0"
# tokio = {version = "1.20.1", features = ["full"]}
